// Date: 4/6/2016 7:27:59 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package simplemods.cheesemod.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelCheeseWheel extends ModelBase
{
  //fields
    ModelRenderer Corner1;
    ModelRenderer Side1;
    ModelRenderer Side2;
    ModelRenderer Corner2;
    ModelRenderer Side3;
    ModelRenderer Corner3;
    ModelRenderer Side4;
    ModelRenderer Corner4;
  
  public ModelCheeseWheel()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      Corner1 = new ModelRenderer(this, 0, 0);
      Corner1.addBox(0F, 0F, 0F, 5, 8, 5);
      Corner1.setRotationPoint(1F, 16F, 4F);
      Corner1.setTextureSize(128, 128);
      Corner1.mirror = true;
      setRotation(Corner1, 0F, 0.7853982F, 0F);
      Side1 = new ModelRenderer(this, 63, 0);
      Side1.addBox(0F, 0F, 0F, 9, 8, 8);
      Side1.setRotationPoint(-4.5F, 16F, -0.5F);
      Side1.setTextureSize(128, 128);
      Side1.mirror = true;
      setRotation(Side1, 0F, 0F, 0F);
      Side2 = new ModelRenderer(this, 32, 0);
      Side2.addBox(0F, 0F, 0F, 8, 8, 8);
      Side2.setRotationPoint(0F, 16F, -4F);
      Side2.setTextureSize(128, 128);
      Side2.mirror = true;
      setRotation(Side2, 0F, 0F, 0F);
      Corner2 = new ModelRenderer(this, 0, 13);
      Corner2.addBox(0F, 0F, 0F, 5, 8, 5);
      Corner2.setRotationPoint(1F, 16F, -4F);
      Corner2.setTextureSize(128, 128);
      Corner2.mirror = true;
      setRotation(Corner2, 0F, 0.7853982F, 0F);
      Side3 = new ModelRenderer(this, 31, 16);
      Side3.addBox(0F, 0F, 0F, 9, 8, 8);
      Side3.setRotationPoint(-4.5F, 16F, -7.5F);
      Side3.setTextureSize(128, 128);
      Side3.mirror = true;
      setRotation(Side3, 0F, 0F, 0F);
      Corner3 = new ModelRenderer(this, 0, 26);
      Corner3.addBox(0F, 0F, 0F, 5, 8, 5);
      Corner3.setRotationPoint(-8F, 16F, 4F);
      Corner3.setTextureSize(128, 128);
      Corner3.mirror = true;
      setRotation(Corner3, 0F, 0.7853982F, 0F);
      Side4 = new ModelRenderer(this, 96, 0);
      Side4.addBox(0F, 0F, 0F, 8, 8, 8);
      Side4.setRotationPoint(-8F, 16F, -4F);
      Side4.setTextureSize(128, 128);
      Side4.mirror = true;
      setRotation(Side4, 0F, 0F, 0F);
      Corner4 = new ModelRenderer(this, 0, 39);
      Corner4.addBox(0F, 0F, 0F, 5, 8, 5);
      Corner4.setRotationPoint(-8F, 16F, -4F);
      Corner4.setTextureSize(128, 128);
      Corner4.mirror = true;
      setRotation(Corner4, 0F, 0.7853982F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5,entity);
    Corner1.render(f5);
    Side1.render(f5);
    Side2.render(f5);
    Corner2.render(f5);
    Side3.render(f5);
    Corner3.render(f5);
    Side4.render(f5);
    Corner4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
  }

}
